### ISSUE TITLE
Clean up vislab-tecnico-lisboa.github.io repository

### ISSUE THREAD

**Issue by gsaponaro** [vislab-tecnico-lisboa/vislab-tecnico-lisboa.github.io#1]
Hi @plinioMoreno , same question here as in https://github.com/vislab-tecnico-lisboa/vislab-tecnico-lisboa.io/issues/1:

this repository seems to have no content, perhaps it was just a test. Can I safely delete it, or do you have some uncommitted stuff that you want to save?

**Comment by plinioMoreno** [comment]
This was probably related to the tests I did to have doxygen working for the repositories at vislab-tecnico-lisboa. I guess this one can be removed.

**Comment by gsaponaro** [comment]
OK thanks, removing this...
